musiclist/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('base/<str:channel>', views.base, name='base'),
    path('search', views.search, name='search'),
    path('artists', views.artists, name='artists'),
    path('artist/<str:artist>', views.artist, name='artist'),
    path('about', views.about, name='about'),
    # these is the browse url
    path('browse', views.browse, name='browse'),
    path('new_song', views.new_song, name='new_song'),
    path('old_song', views.old_song, name='old_song'),
    path('most_listened', views.most_listened, name='most_listened'),
    # path('history', views.history, name='history'),
    path('watchlater', views.watchlater, name='watchlater'),
    path('c/<str:channel>', views.channel, name='channel'),
    path('discover', views.discover, name="discover"),
    path('albums/', views.albums, name='albums'),
    path('cats/<str:category>', views.categorys, name='categorys'),
    path('upload', views.upload, name="upload"),
    # authandications
    path('login', views.login, name='login'),
    path('singup', views.singup, name='singup'),
    path('logout', views.handelLogout, name="handleLogout"),

]

musicnepal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('musiclist/', include('musiclist.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

musiclist/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.shortcuts import reverse
# from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q

# these is for the music length
from .helper import get_audio_length
from .validators import validate_is_audio


class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="cat_imgs/")
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

# these is the backup plan for the modleis the rest oof the plan don't work


class Artist (models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="artist_img/")
    bio = models.TextField(max_length=2000)
    bg_imgs = models.ImageField(default='bg.jpg', upload_to='bg_img/')
    views = models.IntegerField(default=0)
    update = models.DateTimeField(blank=True)

    def __str__(self):
        return self.name


class Song(models.Model):
    song_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=90000)
    singer = models.CharField(max_length=90000)
    category = models.CharField(max_length=90000, default="")
    tags = models.CharField(max_length=90000)
    album_name = models.CharField(max_length=90000)
    time_length = models.DecimalField(
        max_digits=20, decimal_places=2, blank=True)
    song = models.FileField(upload_to='musics/',
                            validators=[validate_is_audio])
    imgofsong = models.ImageField(upload_to='imgofsong', default="0")
    movie = models.CharField(max_length=90000, default="")
    views = models.IntegerField(default=0)
    update = models.IntegerField(default=1)
    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.time_length:
            # logic for getting length of audio
            audio_length = get_audio_length(self.song)
            self.time_length = f'{audio_length:.2f}'

        return super().save(*args, **kwargs)

    class META:
        ordering = "id"

    def __str__(self):
        return f'{self.name}-{self.time_length}'


class Channel(models.Model):
    song_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=2000)
    lastname = models.CharField(max_length=2000)
    bio = models.TextField(max_length=2000)
    # thses is vary imporant to check which person uploaded the  muisc
    music = models.CharField(max_length=90000000)
    # end of  vary imporant to check which person uploaded the  muisc
    imgofablum = models.ImageField(default='user.png', upload_to='imgofablum')
    bgimgofalbum = models.ImageField(default='bg.jpg', upload_to='bg_img/')
    #  upload_to='bgimg/')
    views = models.IntegerField(default=0)
    update = models.DateTimeField(blank=True)

    def __str__(self):
        return self.name


class Favorite(models.Model):
    watch_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video_id = models.CharField(max_length=200000, default="")
    views = models.IntegerField(default=0)
    update = models.DateTimeField(blank=True)

    def __str__(self):
        return f" {self.user} - added music for the watchlater."


class Listenlater(models.Model):
    watch_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video_id = models.CharField(max_length=200000, default="")
    update = models.DateTimeField(blank=True)

    def __str__(self):
        return f" {self.user} - added music for the watchlater."


# class History(models.Model):
#     history_id = models.AutoField(primary_key=True)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     music_id = models.CharField(max_length=200000, default="")

#     def __str__(self):
#         return f" {self.user} - added music for the history."

musiclist/views.py
from django.contrib .auth.models import User
from django.shortcuts import redirect
from django.contrib.auth import authenticate,  login, logout
from django.db.models import Case, When
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView

# these is soptify impornt
from django.http import JsonResponse
# Create your views here.
from .models import *


def base(request, channel):
    song = list(Song.objects.all())
    chan = Channel.objects.filter(name=channel).first()
    video_ids = str(chan.music).split(" ")[1:]
    newsongs = Song.objects.order_by('-song_id',)[0:10]
    preseved = Case(*[When(pk=pk, then=pos)
                      for pos, pk in enumerate(video_ids)])
    song = Song.objects.filter(song_id__in=video_ids).order_by(preseved)
    context = {'chan': chan, 'song': song, 'newsongs': newsongs, }
    return render(request, 'base.html', context)


def browse(request):
    top_10_music = Song.objects.all()[0:12]
    top_10_singer = Artist.objects.all()[0:12]
    top_10_views = Song.objects.order_by('views',)[0:12]
    top_10_date = Song.objects.order_by('-update',)[0:12]
    to_10_cats = Category.objects.all()[0:12]
    newsongs = Song.objects.order_by('-song_id',)[0:10]
    context = {"top_10_music": top_10_music, "top_10_singer": top_10_singer, "top_10_views": top_10_views,
               "top_10_date": top_10_date, "to_10_cats": to_10_cats, "newsongs": newsongs}
    return render(request, 'browse.html', context)

# these is the features section


def new_song(request):
    new_song = Song.objects.order_by('-updated')[0:30]
    context = {'new_song': new_song}
    return render(request, 'new_song.html', context)


def old_song(request):
    old_song = Song.objects.order_by('updated')[0:30]
    context = {'old_song': old_song}
    return render(request, 'old_song.html', context)


def most_listened(request):
    most_listened = Song.objects.order_by('views')[0:30]
    context = {'most_listened': most_listened}
    return render(request, 'most_listened.html', context)


def artists(request):
    newsongs = Song.objects.order_by('-song_id',)[0:10]
    artists = Artist.objects.all()
    context = {'artists': artists, 'newsongs': newsongs}
    return render(request, 'artists.html', context)


def artist(request, artist):
    query = str(artist)
    title = Song.objects.filter(name__icontains=query)  # song
    Allsongsartist = Song.objects.filter(
        singer__icontains=query)  # Allsongsartist_singer
    Allsongstags = Song.objects.filter(tags__icontains=query)
    AllsongsMovie = Song.objects.filter(movie__icontains=query)
    Allsongs = title.union(
        Allsongstags, Allsongsartist, AllsongsMovie)
    print(Allsongs)
    # Artists
    artist_songs = Artist.objects.filter(name__icontains=query)
    newsongs = Song.objects.order_by('-song_id',)[0:10]
    context = {'query': query, 'Allsongs': Allsongs,
               'artist_songs': artist_songs, 'newsongs': newsongs}
    return render(request, 'artist.html', context)


def search(request):
    query = request.GET['query']
    if len(query) > 78:
        Allsongs = Song.objects.none()
    else:
        title = Song.objects.filter(name__icontains=query)  # song
        Allsongsartist = Song.objects.filter(
            singer__icontains=query)  # Allsongsartist_singer
        Allsongstags = Song.objects.filter(tags__icontains=query)
        AllsongsMovie = Song.objects.filter(movie__icontains=query)
        Allsongs = title.union(
            Allsongstags, Allsongsartist, AllsongsMovie)
    # Artists
    artist = Artist.objects.filter(name__icontains=query)
    newsongs = Song.objects.order_by('-song_id',)[0:10]
    params = {'Allsongs': Allsongs, 'query': query,
              'artist': artist, 'newsongs': newsongs}
    return render(request, 'search.html', params)


def history(request):
    # these is the logic for the saving history
    if request.method == "POST":
        user = request.user
        music_id = request.POST['music_id']

        history = History.objects.filter(user=user)
        for i in history:
            if music_id == i.music_id:
                return redirect(f"/musiclist/songs/{music_id}")
        else:
            history = History(user=user, music_id=music_id)
            history.save()
            song = Song.objects.filter(song_id=music_id).first()
            context1 = {
                'song': song,
            }
            return redirect(f"/musiclist/songs/{music_id}")
    history = History.objects.filter(user=request.user)
    ids = []
    for i in history:
        ids.append(i.music_id)
    preseved = Case(*[When(pk=pk, then=pos) for pos, pk in enumerate(ids)])
    song = Song.objects.filter(song_id__in=ids).order_by(preseved)
    context = {
        'song': song
    }
    return render(request, 'history.html', context)


def watchlater(request):
    newsongs = Song.objects.order_by('-song_id',)[0:10]
    # these is the logic for the saving watchlater
    if request.method == "POST":
        user = request.user
        video_id = request.POST['video_id']

        watch = Watchlater.objects.filter(user=user)
        for i in watch:
            if video_id == i.video_id:
                msg = "your video is already Added"
                return redirect(f"/musiclist/songs/{video_id}")
        else:
            watchlater = Watchlater(user=user, video_id=video_id)
            watchlater.save()
            msg = "your video is  Added for watch latter."
            song = Song.objects.filter(song_id=video_id).first()
            context1 = {
                'song': song,
                'msg': msg
            }
            return redirect(f"/musiclist/songs/{video_id}", context1)
    wl = Watchlater.objects.filter(user=request.user)
    ids = []
    for i in wl:
        ids.append(i.video_id)
    preseved = Case(*[When(pk=pk, then=pos) for pos, pk in enumerate(ids)])
    song = Song.objects.filter(song_id__in=ids).order_by(preseved)
    context2 = {
        'song': song,
        'newsongs': newsongs,
    }
    return render(request, 'favourite.html', context2)


def upload(request):

    if request.method == "POST":
        # Get the post parameters
        name = request.POST['name']
        singer = request.POST['singer']
        category = request.POST['category']
        tags = request.POST['tags']
        album_name = request.POST['album_name']
        imgofsong = request.FILES['imgofsong']
        movie = request.POST['movie']
        song = request.FILES['file']
        update = request.POST['update']

        song_model = Song(name=name, singer=singer, category=category, tags=tags, album_name=album_name,
                          imgofsong=imgofsong, song=song, movie=movie, update=update,)
        song_model.save()

        music_id = song_model.song_id
        channel_find = Channel.objects.filter(name=str(request.user))

        for i in channel_find:
            i.music += f" {music_id}"
            i.save()
        # Create the user
    cats = Category.objects.all()
    #     catvalues = Category.objects.values("id", "image", "title")
    #     print(catvalues)
    context = {"cats": cats, }
    return render(request, 'upload.html', context)


def channel(request, channel):
    chan = Channel.objects.filter(name=channel).first()
    video_ids = str(chan.music).split(" ")[1:]
    newsongs = Song.objects.order_by('-song_id',)[0:10]
    preseved = Case(*[When(pk=pk, then=pos)
                      for pos, pk in enumerate(video_ids)])
    song = Song.objects.filter(song_id__in=video_ids).order_by(preseved)
    context = {'chan': chan, 'song': song, 'newsongs': newsongs, }
    return render(request, 'channel.html', context)


def albums(request):
    chan = Channel.objects.all()
    cats = Category.objects.all()
    newsongs = Song.objects.order_by('-song_id',)[0:10]
    context = {'cats': cats, 'chan': chan, 'newsongs': newsongs, }
    return render(request, 'albums.html', context)


def discover(request):
    discoverys = Category.objects.all()
    newsongs = Song.objects.order_by('-song_id',)[0:10]
    context = {'discoverys': discoverys, 'newsongs': newsongs, }
    return render(request, "discoverys.html", context)


def categorys(request, category):
    newsongs = Song.objects.order_by('-song_id',)[0:10]
    query = str(category)
    allsongcatsTitle = Song.objects.filter(name__icontains=query)
    allsongcatsinger = Song.objects.filter(singer__icontains=query)
    allsongcatstags = Song.objects.filter(tags__icontains=query)
    allsongcatstags = Song.objects.filter(category__icontains=query)
    allsongcatsMovie = Song.objects.filter(movie__icontains=query)
    allsongcats = allsongcatsTitle.union(
        allsongcatstags, allsongcatsinger, allsongcatsMovie)
    context = {'allsongcats': allsongcats, 'newsongs': newsongs, }
    return render(request, 'categorys.html', context)


def login(request):
    if request.method == "POST":
        # Get the post parameters
        loginusername = request.POST['loginusername']
        loginpassword = request.POST['loginpassword']
        user = authenticate(username=loginusername, password=loginpassword)
        from django.contrib.auth import login
        login(request, user)
        return redirect('/')
    return render(request, 'login.html')


def singup(request):
    if request.method == "POST":
        # Get the post parameters
        username = request.POST['username']
        email = request.POST['email']
        fname = request.POST['fname']
        lname = request.POST['lname']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']
        # Create the user
        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name = fname
        myuser.last_name = lname
        myuser.save()
        user = authenticate(username=username, password=pass1)
        from django.contrib.auth import login
        login(request, user)

musiclist/templates/about.html
{% extends 'base.html' %}
{% block title %}
 About
{% endblock title %}
{% block body %}
<article class="my-3" id="scrollspy">
      <div class="bd-heading sticky-xl-top align-self-start mt-5 mb-3 mt-xl-0 mb-xl-2">
        <h3>Scrollspy</h3>
        <a class="d-flex align-items-center" href="../components/scrollspy/">Documentation</a>
      </div>

      <div>
        <div class="bd-example">
          <nav id="navbar-example2" class="navbar navbar-light bg-light px-3">
            <a class="navbar-brand" href="#">Navbar</a>
            <ul class="nav nav-pills">
              <li class="nav-item">
                <a class="nav-link active" href="#scrollspyHeading1">First</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#scrollspyHeading2">Second</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Dropdown</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#scrollspyHeading3">Third</a></li>
                  <li><a class="dropdown-item" href="#scrollspyHeading4">Fourth</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#scrollspyHeading5">Fifth</a></li>
                </ul>
              </li>
            </ul>
          </nav>
        <div data-bs-spy="scroll" data-bs-target="#navbar-example2" data-bs-offset="0" class="scrollspy-example" tabindex="0">
            <h4 id="scrollspyHeading1">First heading</h4>
            <p>This is some placeholder content for the scrollspy page. Note that as you scroll down the page, the appropriate navigation link is highlighted. It's repeated throughout the component example. We keep adding some more example copy here to emphasize the scrolling and highlighting.</p>
            <h4 id="scrollspyHeading2">Second heading</h4>
            <p>This is some placeholder content for the scrollspy page. Note that as you scroll down the page, the appropriate navigation link is highlighted. It's repeated throughout the component example. We keep adding some more example copy here to emphasize the scrolling and highlighting.</p>
            <h4 id="scrollspyHeading3">Third heading</h4>
            <p>This is some placeholder content for the scrollspy page. Note that as you scroll down the page, the appropriate navigation link is highlighted. It's repeated throughout the component example. We keep adding some more example copy here to emphasize the scrolling and highlighting.</p>
            <h4 id="scrollspyHeading4">Fourth heading</h4>
            <p>This is some placeholder content for the scrollspy page. Note that as you scroll down the page, the appropriate navigation link is highlighted. It's repeated throughout the component example. We keep adding some more example copy here to emphasize the scrolling and highlighting.</p>
            <h4 id="scrollspyHeading5">Fifth heading</h4>
            <p>This is some placeholder content for the scrollspy page. Note that as you scroll down the page, the appropriate navigation link is highlighted. It's repeated throughout the component example. We keep adding some more example copy here to emphasize the scrolling and highlighting.</p>
          </div>
        </div>
      </div>
    </article>

<div class="row position-fix">
              <div class="col-4"> <a href="#freaures">freaures</a> </div>
              <div class="col-4"> <a href="#copyright_issue">copyright_issue</a> </div>
              <div class="col-4"> <a href="#for_singer_and_authers">for_singer_and_authers</a> </div>
              <div class="col-4"> <a href="#q_and_a"></a> </div>
</div>
               <div class="row mt-4">
        <div class="col-md-8 blog-main">


              <section id="freaures">

              </section>

              <section id="copyright_issue">

              </section>

              <section id="q_and_a">

              </section>
              

              <section id="for_singer_and_authers">
                            <strong>If the Singer or the user have any Problem with these website.</strong>
              <p>We sinserly aploize for the trobble . If you have problem with these website plase try to inform us with the informantions given in the aside section.</p>
              <p>We don't wanna to make the problems for anyone . We just wanna to help the singer/indersrty/new_grenerations with these platfrom . We all try our best to 
                            improve conditions of the music indersrty of the nepal . 
                            If the make these possible it will help to the newer generations to 
                            achive there dreams with there own motive .</p>

                            <p>As we all know that our country is the developing country .
                            The people of the nepal cannot affort there own set of the songs/albums 
                            these website will help them the listen the songs freely.
                            </p>

              </section>


        </div>
        <!-- /.blog-post -->
        <aside class="col-md-4 blog-sidebar">
            <div class="p-4 mb-3 bg-dark rounded">
                          <h6><strong>Admin: Alan Thapa, Binita Chattery,Siddhant Aryal , Schain loed, Arjun Harijan.   </strong></h6>
                          <h6><strong>contact/Phone:1234567890 / 1234567890 / 1234567890</strong></h6>
                            <h6><h6><strong>Email:NepaliSong@gmail.com </strong></h6></h6>
                          <h6><strong>Location: Ruphandehi </strong></h6>
                          <strong>© 2021 • NepaliSong.com</strong>
            </div>



            <div class="p-4">
                <h4 class="font-italic">Elsewhere</h4>
                <ol class="list-unstyled">
                    <li><a href="#"> <i class="fab fa-twitter "></i> Twitter</a></li>
                    <li><a href="#"> <i class="fab fa-facebook "></i> Facebook</a></li>
                </ol>
            </div>
        </aside><!-- /.blog-sidebar -->

    </div><!-- /.blog-main -->

{% endblock body %}
{% block music_manu %}
 <h6 class="text-center">Sorry, Music menu features are not add yet ! We will try to add in the future . </h1>
<p class="text-center">© CopyRight 2021 • NepaliSong</p>

             
{% endblock music_manu %}

musiclist/templates/albums.html
{% extends 'base.html' %}
{% block albums %} active {% endblock albums %}
{% block title %}
Albums
{% endblock title %}
{% block body %}

   <div   class="row text-center m-1  topic">
            <div class="col-12 bg_img bg-dark m-2 p-4 ">
                   <h3>NepaliSong.com</h3>
                  <h4>Top 30 Nepali Tranding Albums! </h4>
                  <h4> of 2021 comming soon....</h4>
            </div>
      </div>


    <div class="postion-scroll">
  <div class="row mt-1 ">


            

{% for i in chan %}


                                          <div class="col-2 col-md-2 col-lg-2 p-0 wapper_albums ">
                                          <div>
                                          <img class="wapper_albums_img p-0 m-0 "
                                                        src="{{i.imgofablum.url}}">
                                          </div>
                                          <div class="content">
                                          <div class="info">
                                                        <h6> {{i.name}}</h6>
                                                        <h6>Album</h6>
                                          </div>
                                          </div>
                                          <!-- <ul>
                                                        <li><a class="anker" href="/musiclist/c/{{i.name}}"><span class="fa fa-play text-center"></span></a></li>
                                                        <li><a class="anker" href="/musiclist/c/{{i.name}}"><span class="fab fa-twitter text-center"></span></a></li>
                                                        
                                          </ul> -->
                                          </div>


                       
                            {% endfor %}
                                                   


  </div>
</div>

{% endblock body %}
 {% block music_menu %}     
<h6 class="text-center">Sorry , Music menu features are not add yet ! We will try to add in the future . </h1>
<p class="text-center">© CopyRight 2021 • NepaliSong</p>


 {% endblock %}

musiclist/templates/artists.html
{% extends 'base.html' %}
{% block artists %} active {% endblock artists %}
{% block title %}
Artists
{% endblock title %}
{% block body %}




<div class="row mt-2 ">

{% for i in artists %}

<div class="col-6 col-md-2 col-lg-2 wapper_artist">
 <a class="anker" href="/musiclist/artist/{{i.name}}">
 <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                                                        src="{{i.image.url}}">

        <h6 class=" text-center">{{i.name}}</h6>
   </a>
      </div>                   
   {% endfor %}
</div>
{% endblock body %}

 {% block music_menu %}     
<h6 class="text-center">Sorry, Music menu features are not add yet ! We will try to add in the future . </h1>
<p class="text-center">© CopyRight 2021 • NepaliSong</p>
 {% endblock %}

musiclist/templates/favourite.html
{% extends 'base.html' %}
{% block favourite %} active {% endblock favourite %}
{% block title %} Watch later {% endblock title %}
{% block body %}
<div class="container my-3">
      {% if song|length < 1 %} <h1> Oops! look like You have not save any music for theNew Songs.</h1>

      {% endif %}
      {% for song in song %}
      <div
            class="row extradiv no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
            <div class="col-3">
                  <img src="{{song.image.url}}" alt="" height='234' width="100%">
            </div>
            <div class="col-9 p-4 d-flex flex-column position-static">
                  <strong class="d-inline-block mb-2 text-primary">Album of: {{song.singer}}</strong>
                  <h3 class="mb-0">{{song.name}}</h3>
                  <div class="mb-1 text-muted">{{song.tags}}</div>
                  <p class="card-text mb-auto">{{song.movie| truncatechars:500}}</p>

                  <a href="/musiclist/songs/{{song.song_id}}">
                        <button class="btn btn-primary">listen Song</button> </a>
            </div>
      </div>


      
      {% endfor %}
</div>
{% endblock %}

musiclist/templates/upload.html
{% extends 'base.html' %}
{% block title %}
Upload you music
{% endblock title %}
{% block body %}
<div class="container m-4 p-4 ">
      <h2 class="text-center">Upload Your Music </h2>
      <form action="/musiclist/upload" enctype="multipart/form-data" method='post'>
            {% csrf_token %}
            <div class="form-group">
                  <label for="username">Music name: " _  and  _-_ " are not alloded play make sure that.</label>
                  <input type="text" class="form-control" id="username" name="name"
                        placeholder="Enter your music name... " required>
            </div>
            <div class="form-group">
                  <label for="fname">Singer name:</label>
                  <input type="text" class="form-control" id="fname" name="singer"
                        placeholder="Enter the name of singer... " required>
            </div>
                       

            <div class="form-group"> 
                  <label for="id_category">Select Category of the song:</label>
                  <select name="category" id="id_category" style="height: 39px;width: 81.1%;">
                  {% for i in cats  %}
                  <option value="{{i.title}}" style="text-transform: capitalize;">{{i.title}}</option>
                  {% endfor %}
                  </select>
            </div>

            <div class="form-group">
                  <label for="tag">Tags - Neme of music and singer are important :</label>
                  <input type="text" class="form-control" id="tag" name="tags"
                        placeholder="Enter the type of song...  " required>
            </div>
            
            <div class="form-group">
                  <label for="album_name">Album:</label>
                  <input type="text" class="form-control" id="album_name" name="album_name"
                        placeholder="Enter the type of song...  " required>
            </div> 

            <div class="form-group">
                  <label for="img">Select a image:</label>
                  <input type="file" class="form-control-file" id="filesToUpload2" multiple="multiple" name='imgofsong'
                        required>
            </div>


            <div class="form-group">
                  <label for="movie">Movie:</label>
                  <input type="text" class="form-control" id="movie" name="movie"
                        placeholder="Enter the name of movie or type no movie... " required>
            </div>

            <div class="form-group">
                  <label for="video">Select a Audio file:</label>
                  <input type="file" class="form-control-file" id="filesToUpload2" multiple="multiple" name='file'
                        required>
            </div>


            <div class="form-group">
                  <label for="update">Date of release:</label>
                  <input type="text" class="form-control" id="update" name="update"
                        placeholder="Enter the song release date..." required>
            </div>
            {% csrf_token %}
            <button type="submit" class="btn btn-block btn-primary p-2  ">Submit</button>
      </form>



</div>

{% endblock body %}



 {% block music_menu %}     
<h6 class="text-center">Sorry. Music menu features are not add yet ! We will try to add in the future . </h1>
<p class="text-center">© CopyRight 2021 • NepaliSong</p>
 {% endblock %}